//! Staging a Release Bundle: the one publication engine the CLI and the desktop share.
//!
//! The placement is deliberate. Prompt §36 puts portable *content* in `firmwaresight-report` and bundle
//! *publication* in the application layer, while §35 requires the CLI and the desktop to run the same
//! staging/swap engine and §65 forbids a sixth crate. A crate that already reads config, Release Notes and
//! Git, and already owns `sha2`, is the only place that satisfies all three at once — the arrangement is
//! recorded in `.ai/DECISIONS.md` as "Two crates share the work". What follows from it is the edge this
//! module keeps: `report` composes bytes, this module verifies, stages, publishes and re-reads them, and
//! neither decides what a Gate state means. Core does, through the P3 adapter in [`crate::evidence`].
//!
//! ```text
//! facts from the app ─▶ observe() ─▶ BundlePlan ─▶ publish() ─▶ <bundle-root>/
//!   snapshot, git,      §9 §8 §11    §27 preview    §28 §31      §7 layout
//!   config, reviews     §22 §23 §24  §42 bytes      §30 §32      §44 verified
//! ```
//!
//! Three properties hold the design together:
//!
//! 1. **A bundle is a verdict output, not an export of whatever is on screen.** Preparation re-observes the
//!    project, rebuilds the Gate context through the same adapter that produced the stored run, and refuses
//!    unless the run id it recomputes equals the run that was selected (§9). A stale `PASS` over a newly
//!    dirty workspace therefore produces no bundle.
//! 2. **The plan is the payload.** [`prepare`] composes every generated byte, hashes it, and keeps the
//!    result; [`BundlePlan::publish`] writes those same bytes and never re-renders anything. That is what
//!    makes §41's ordering enforceable instead of aspirational: the report is composed before `SHA256SUMS`,
//!    `SHA256SUMS` before the manifest, and nothing is regenerated after the manifest exists.
//! 3. **Nothing destructive happens to a directory this engine did not write.** An existing destination is
//!    refused (§30); with explicit authorization it is first required to be a recognizable FirmwareSight
//!    bundle (§32), then renamed aside, then replaced, then discarded — and a failed swap puts the backup
//!    back. An arbitrary user directory is never recursively deleted, `overwrite` notwithstanding.
//!
//! Host paths stop at this boundary in both directions. A source path enters as an input; every value that
//! leaves — preview, plan, verification, error text — names a bundle-relative path or a display leaf
//! (`AGENTS.md` 7, prompt §27, §29).

use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicUsize, Ordering};

use firmwaresight_core::domain::build_snapshot::BuildSnapshot;
use firmwaresight_core::domain::diff::DiffResult;
use firmwaresight_core::domain::gate::{
    EffectiveSeverity, FindingState, GateContext, GateEvaluation, GateFileStatus, GateGrowthFacts,
    GatePolicy, GateRuleId,
};
use firmwaresight_core::domain::identity::{ArtifactKind, Sha256};
use firmwaresight_core::domain::release::{
    ACCEPTED_REVIEWS_DOC_NAME, ANALYSIS_DOC_NAME, ARTIFACTS_DIR, DIFF_DOC_NAME,
    GATE_RESULTS_DOC_NAME, MANIFEST_DOC_NAME, RELEASE_NOTES_NAME, REPORT_DOC_NAME, ReleaseArtifact,
    ReleaseError, ReleaseId, ReleaseModel, ReleaseNotesDigest, ReleaseVersion,
    ReleaseVersionSource, SHA256SUMS_NAME, SUMS_EXCLUDED_NAMES, SchemaMajors, WorkspaceGit,
    bundle_path_order, disambiguated_name, is_safe_bundle_relative_path, require_packageable,
    sanitize_leaf_name,
};
use firmwaresight_report::analysis::AnalysisDocumentDto;
use firmwaresight_report::diff::DiffResultDto;
use firmwaresight_report::gate::{
    ACCEPTANCE_ORIGINAL_STATE, AcceptanceDto, AcceptedReviewsDto, GateResultsDto,
};
use firmwaresight_report::release::{ManifestError, ManifestFileDto, ReleaseManifestDto};
use firmwaresight_report::release_render::{
    self, CompareSummary, REPORT_GROWTH_ROWS, ReleaseBundleReport,
};
use firmwaresight_report::render::document_json;
use firmwaresight_report::schemas;

use crate::config::LoadedProject;
use crate::evidence::{self, SnapshotFacts};
use crate::fingerprint;
use crate::git::GitObservation;

/// The files every bundle carries: §7's layout minus the two that depend on the release.
const REQUIRED_BUNDLE_FILES: [&str; 6] = [
    ANALYSIS_DOC_NAME,
    GATE_RESULTS_DOC_NAME,
    ACCEPTED_REVIEWS_DOC_NAME,
    REPORT_DOC_NAME,
    SHA256SUMS_NAME,
    MANIFEST_DOC_NAME,
];

/// The two files a release may or may not carry. Anything outside these eight names, `SHA256SUMS` and the
/// manifest included, is not a bundle file — which is how a stray temp or log file is caught rather than
/// indexed (§44's "no unexpected temp file").
const OPTIONAL_BUNDLE_FILES: [&str; 2] = [DIFF_DOC_NAME, RELEASE_NOTES_NAME];

/// The documents this engine composes, and which must therefore carry no host path anywhere in them.
///
/// `release-notes.md` and the files under `artifacts/` are deliberately absent: they are the release owner's
/// bytes, copied byte-for-byte (§24, §22), and a path inside a sentence about the release is their business
/// rather than a leak from this engine. `SHA256SUMS` is checked through its own parsed entries.
const GENERATED_TEXT_DOCUMENTS: [&str; 6] = [
    ANALYSIS_DOC_NAME,
    DIFF_DOC_NAME,
    GATE_RESULTS_DOC_NAME,
    ACCEPTED_REVIEWS_DOC_NAME,
    REPORT_DOC_NAME,
    MANIFEST_DOC_NAME,
];

/// Every way publication refuses, with the §51 code a UI can show and a report can quote.
///
/// Each message states what happened and what the release owner does next, because the commonest of these is
/// not a bug: it is a workspace that moved after the Gate ran.
#[derive(Debug, thiserror::Error)]
pub enum BundleError {
    /// The disposition after the accepted reviews is not `PASS`, no version could be resolved, or nothing
    /// was selected to ship (§8, §11). Core owns those refusals, so its error is carried through rather than
    /// re-described here — and `ERR-BUNDLE-6101`/`6110` are named in one place.
    #[error(transparent)]
    Release(#[from] ReleaseError),

    /// The assembled index refused the assembled content: the bundle as computed is not a bundle this build
    /// would write, so nothing was written.
    #[error(transparent)]
    Index(#[from] ManifestError),

    /// The run that was selected is not the run this context produces (§9).
    #[error(
        "the Gate run selected is `{selected}` but the current project context recomputes to \
         `{recomputed}`: the workspace, configuration or Release Notes moved after that run was recorded"
    )]
    GateContextChanged {
        selected: String,
        recomputed: String,
    },

    /// A source file is missing, not regular, unreadable, or no longer the bytes the snapshot hashed (§22).
    #[error("the source of `{name}` is not the bytes the build recorded: {detail}")]
    SourceArtifactChanged { name: String, detail: String },

    /// The Release Notes are not the bytes the recomputed context observed (§24).
    #[error("the Release Notes are not the bytes the Gate observed: {detail}")]
    ReleaseNotesChanged { detail: String },

    /// Something the preview was built from changed between preview and export (§28).
    #[error("the bundle plan is stale: {detail}")]
    PlanStale { detail: String },

    /// The destination directory already exists and this export was not authorized to replace it (§30).
    #[error(
        "`{display}` already exists in the chosen folder, and exporting would replace the bundle that is \
         there"
    )]
    DestinationExists { display: String },

    /// Replacement was authorized, but the existing directory is not a recognizable FirmwareSight bundle,
    /// so it is somebody else's data (§31, §32).
    #[error("refused to replace `{display}`: {detail}")]
    UnsafeDestination { display: String, detail: String },

    /// A write, flush or rename failed. The staged tree was discarded and the destination is untouched.
    #[error("could not write `{name}` into the bundle: {detail}")]
    WriteFailed { name: String, detail: String },

    /// What was written does not match what the bundle records about itself (§31 step 10, §44).
    #[error("the bundle did not verify: {detail}")]
    VerificationFailed { detail: String },

    /// A structural expectation of this module was violated, which is a bug rather than user input.
    #[error("internal invariant violated: {detail}")]
    Internal { detail: String },
}

impl BundleError {
    /// The stable diagnostics code.
    #[must_use]
    pub fn code(&self) -> &'static str {
        match self {
            Self::Release(error) => error.code(),
            Self::Index(_) | Self::VerificationFailed { .. } => "ERR-BUNDLE-6109",
            Self::GateContextChanged { .. } => "ERR-BUNDLE-6102",
            Self::SourceArtifactChanged { .. } => "ERR-BUNDLE-6103",
            Self::ReleaseNotesChanged { .. } => "ERR-BUNDLE-6104",
            Self::PlanStale { .. } => "ERR-BUNDLE-6105",
            Self::DestinationExists { .. } => "ERR-BUNDLE-6106",
            Self::UnsafeDestination { .. } => "ERR-BUNDLE-6107",
            Self::WriteFailed { .. } => "ERR-BUNDLE-6108",
            Self::Internal { .. } => "ERR-INTERNAL-9004",
        }
    }

    /// What the release owner can do next. §51 forbids a stack trace in a UI, so this sentence, shown under
    /// the error, is the whole of the remediation surface.
    #[must_use]
    pub fn remediation(&self) -> &'static str {
        match self {
            Self::Release(ReleaseError::VersionUnavailable { .. }) => {
                "configure a version policy and an expected version, or tag the release so the pattern \
                 captures one, then run the Gate again"
            }
            Self::Release(_) => {
                "run the Gate again and resolve what it reports: a bundle is written only for a PASS \
                 disposition"
            }
            Self::Index(_) | Self::VerificationFailed { .. } => {
                "keep whatever was written, and report the release id and the Gate run id: a bundle that \
                 does not verify against itself is evidence, not something to retry over the top of"
            }
            Self::GateContextChanged { .. } => "run the Gate again and review the new result",
            Self::SourceArtifactChanged { .. } => {
                "re-analyze the intended artifact, or restore the exact bytes. A snapshot's hash is never \
                 updated to match a file that moved"
            }
            Self::ReleaseNotesChanged { .. } => {
                "restore the notes the Gate read, or run the Gate again over the new ones"
            }
            Self::PlanStale { .. } => "prepare the bundle again",
            Self::DestinationExists { .. } => {
                "choose another folder, or confirm the replacement explicitly"
            }
            Self::UnsafeDestination { .. } => {
                "choose another folder: only a directory FirmwareSight wrote as a release bundle is \
                 eligible for replacement"
            }
            Self::WriteFailed { .. } => {
                "check the free space and permissions of the chosen folder, then prepare the bundle again"
            }
            Self::Internal { .. } => {
                "report the release id and the Gate run id; no bundle was written"
            }
        }
    }
}

// --------------------------------------------------------------------------- inputs

/// One accepted review, as the caller's storage holds it (§10).
///
/// Deliberately not a `firmwaresight-storage` type: ADR-0027 keeps this crate off the database, so the app
/// hands the audit fields across and this module never learns where they were stored.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BundleAcceptance {
    pub finding_id: String,
    pub actor: String,
    /// The stored `accepted_at`. It is an audit fact already in the record, which §25 allows into a
    /// document; it is never a generation timestamp.
    pub accepted_at: String,
    pub reason: String,
}

/// Everything preparation observes, as facts the calling surface already holds.
#[derive(Debug, Clone)]
pub struct BundleRequest<'a> {
    /// The loaded project: its root, its policy, and that policy's fingerprint (§28 re-checks it).
    pub project: &'a LoadedProject,
    /// Git re-observed now, not the facts stored with the run.
    pub git: &'a GitObservation,
    /// The build that ships. Its artifact rows carry the source paths this module re-reads (§22).
    pub snapshot: &'a BuildSnapshot,
    /// The comparison the Gate's growth rule was judged from, when the release has a baseline. Reused, not
    /// recomputed: Core's diff stays the only place a delta is calculated (§23).
    pub comparison: Option<&'a DiffResult>,
    /// The run the release owner selected, when a stored run was selected. `None` is the headless case,
    /// where the run is computed in this same process and there is no older record to disagree with (§9).
    pub selected_run_id: Option<&'a str>,
    /// The acceptances recorded against `selected_run_id`.
    pub acceptances: &'a [BundleAcceptance],
    /// The FirmwareSight build assembling the bundle, kept distinct from the project release version in
    /// every output (§43).
    pub fwsight_version: &'a str,
}

// --------------------------------------------------------------------------- plan

/// What a file in the bundle is, in the preview's words (§27).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FileRole {
    /// A current firmware artifact, shipped under `artifacts/` (§23).
    ShippedArtifact,
    Analysis,
    Comparison,
    GateResults,
    AcceptedReviews,
    ReleaseNotes,
    Report,
    /// `SHA256SUMS`.
    ChecksumIndex,
    /// `release-manifest.json`.
    Manifest,
}

impl FileRole {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ShippedArtifact => "artifact",
            Self::Analysis => "analysis",
            Self::Comparison => "comparison",
            Self::GateResults => "gate-results",
            Self::AcceptedReviews => "accepted-reviews",
            Self::ReleaseNotes => "release-notes",
            Self::Report => "report",
            Self::ChecksumIndex => "checksum-index",
            Self::Manifest => "manifest",
        }
    }
}

/// One file the plan will write, as a preview may describe it (§27).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PlannedFile {
    /// Bundle-relative and `/`-separated, validated by Core's single path rule.
    pub path: String,
    pub role: FileRole,
    pub byte_size: u64,
    /// Always known: a file this engine cannot hash is refused during preparation rather than listed with a
    /// blank digest, so §27's "when known at planning" never leaves a hole in what a reader sees.
    pub sha256: String,
}

/// The bounded, path-free shape of a plan — the only part of it that may cross into a UI (§27, §29).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BundlePreview {
    /// Session-local and opaque: it names this plan to this process and means nothing anywhere else. It is
    /// not persisted, not portable, and not the release id (§26).
    pub plan_id: String,
    pub release_id: String,
    pub release_version: String,
    pub snapshot_id: String,
    pub baseline_snapshot_id: Option<String>,
    pub gate_run_id: String,
    /// `PASS`, always: §8 refuses to plan anything else, so this is a promise rather than a status.
    pub disposition: &'static str,
    pub files: Vec<PlannedFile>,
    /// The configuration findings the release was prepared under. Path-free by construction, and the only
    /// warnings a plan carries: comparison warnings belong to the bytes they describe, and live in
    /// `diff.json` and in the report's own limits section.
    pub warnings: Vec<String>,
}

/// A verified bundle that has not been written yet, holding every byte it would write.
#[derive(Debug, Clone)]
pub struct BundlePlan {
    /// What the release owner authorizes before any write.
    pub preview: BundlePreview,
    content: BundleContent,
    checks: InputChecks,
}

impl BundlePlan {
    /// The directory name this bundle proposes inside the folder the release owner chose (§29):
    /// `<sanitized-project>-<release-version>-<release-id-short>`. It is a display name, not a path, which
    /// is what lets a UI show and confirm it without ever receiving a host path.
    #[must_use]
    pub fn proposed_directory_name(&self) -> &str {
        &self.content.directory_name
    }

    /// The `release-manifest.json` document exactly as written, for the CLI's `--json` contract (§34): the
    /// stdout copy and the bundle copy are one string, so they cannot be two documents.
    #[must_use]
    pub fn manifest_document(&self) -> &str {
        &self.content.manifest_json
    }

    /// Write the bundle.
    ///
    /// `fresh` is the same request re-collected after the preview — current source digests, current config,
    /// current Git facts, current acceptance set. Anything that moved since [`prepare`] invalidates the plan
    /// and nothing is written (§28). `overwrite` is the release owner's explicit authorization to replace an
    /// existing bundle directory (§30), honored only for a directory recognizable as a FirmwareSight release
    /// bundle (§32).
    ///
    /// # Errors
    ///
    /// [`BundleError::PlanStale`], [`BundleError::SourceArtifactChanged`],
    /// [`BundleError::ReleaseNotesChanged`], [`BundleError::DestinationExists`],
    /// [`BundleError::UnsafeDestination`], [`BundleError::WriteFailed`],
    /// [`BundleError::VerificationFailed`] or [`BundleError::Index`], as described on [`BundleError`].
    pub fn publish(
        &self,
        fresh: &BundleRequest<'_>,
        parent: &Path,
        overwrite: bool,
    ) -> Result<BundleOutcome, BundleError> {
        let again = observe(fresh)?;
        self.checks.compare_with(&again.checks)?;

        let display = self.content.directory_name.clone();
        let destination = parent.join(&display);
        if destination.exists() {
            if !overwrite {
                return Err(BundleError::DestinationExists { display });
            }
            if !is_recognizable_bundle(&destination)? {
                return Err(BundleError::UnsafeDestination {
                    display,
                    detail: "it holds no `release-manifest.json` this build can read as a FirmwareSight \
                             release bundle, so it is not a bundle this engine wrote"
                        .to_owned(),
                });
            }
        } else {
            std::fs::create_dir_all(parent).map_err(|error| BundleError::WriteFailed {
                name: ".".to_owned(),
                detail: io_detail(&error),
            })?;
        }

        // §31, in order: a unique sibling staging directory, the payload, the two indexes, verification of
        // the staged tree, and only then the rename that makes it somebody's bundle.
        let staging = sibling(parent, "staging");
        if let Err(error) = write_tree(&self.content, &staging) {
            discard(&staging);
            return Err(error);
        }
        if let Err(error) = verify_bundle(&staging) {
            discard(&staging);
            return Err(error);
        }

        let backup = match replace_directory(&staging, &destination, overwrite, &display) {
            Ok(backup) => backup,
            Err(error) => {
                discard(&staging);
                return Err(error);
            }
        };
        let verification = verify_bundle(&destination)?;
        if let Some(previous) = &backup {
            // The predecessor is discarded only once the new bundle is in place and verified (§31).
            std::fs::remove_dir_all(previous).map_err(|error| BundleError::WriteFailed {
                name: display.clone(),
                detail: format!(
                    "the new bundle is published; the bundle it replaced is still in the folder under \
                     its original name and could not be discarded ({})",
                    error.kind()
                ),
            })?;
        }

        Ok(BundleOutcome {
            plan_id: self.preview.plan_id.clone(),
            release_id: self.content.release_id.clone(),
            release_version: self.content.model.version.as_str().to_owned(),
            gate_run_id: self.content.model.gate_run_id.clone(),
            directory_name: display,
            manifest_sha256: self.content.manifest_sha256.clone(),
            replaced: backup.is_some(),
            verification,
        })
    }
}

/// What publication produced, in the facts the caller can persist and show.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BundleOutcome {
    pub plan_id: String,
    pub release_id: String,
    pub release_version: String,
    pub gate_run_id: String,
    /// The bundle's own directory name. Not a path: the caller chose the parent and already knows it.
    pub directory_name: String,
    /// The digest of `release-manifest.json` as written — the fact that ties a release record to a
    /// directory without naming one (§37).
    pub manifest_sha256: String,
    /// True when an existing recognized bundle was replaced under explicit authorization.
    pub replaced: bool,
    pub verification: BundleVerification,
}

/// The facts one verified bundle states about itself (§44).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BundleVerification {
    pub release_id: String,
    pub file_count: usize,
    pub total_bytes: u64,
    pub artifact_count: usize,
    /// Whether the bundle carries `diff.json`, read from the bytes rather than inferred.
    pub carries_comparison: bool,
    /// Whether the bundle carries `release-notes.md`.
    pub carries_release_notes: bool,
}

// --------------------------------------------------------------------------- preparation

/// Prepare a bundle: §26's steps 1 through 14, ending in a preview and an opaque plan id.
///
/// Nothing is written here. A plan holds the exact bytes it would write, so the preview a release owner
/// authorized and the bundle that appears in their folder cannot turn out to be two different documents.
///
/// # Errors
///
/// Any [`BundleError`] except the destination-dependent ones: preparation has not looked at a folder yet.
pub fn prepare(request: &BundleRequest<'_>) -> Result<BundlePlan, BundleError> {
    let observed = observe(request)?;
    Ok(BundlePlan {
        preview: observed.content.preview(next_plan_id()),
        content: observed.content,
        checks: observed.checks,
    })
}

/// What §26's steps read and check, before any plan id or destination exists.
struct Observation {
    content: BundleContent,
    checks: InputChecks,
}

/// The re-checkable identity of a plan's inputs (§28).
///
/// Source paths appear here and nowhere else: they are the caller's own strings, kept private so they cannot
/// reach a preview, a portable document, or even an error message.
#[derive(Debug, Clone, PartialEq, Eq)]
struct InputChecks {
    run_id: String,
    policy_sha256: String,
    acceptances_sha256: String,
    /// `(source path as recorded, digest, size)` for every shipped row, in snapshot order.
    sources: Vec<(String, String, u64)>,
    /// `(project-relative notes path, digest, size)`, when the policy asked for notes at all.
    notes: Option<(String, String, u64)>,
}

impl InputChecks {
    /// Report the first thing that moved, naming it in the terms §28 lists. A source or notes change keeps
    /// its own §51 code, because its remediation is about the file rather than about the plan.
    fn compare_with(&self, now: &Self) -> Result<(), BundleError> {
        if self.sources != now.sources {
            return Err(BundleError::SourceArtifactChanged {
                name: changed_leaf(&self.sources, &now.sources),
                detail: "the file was read again at export and is no longer the bytes the preview hashed"
                    .to_owned(),
            });
        }
        if self.notes != now.notes {
            return Err(BundleError::ReleaseNotesChanged {
                detail: "the file was read again at export and is no longer the bytes the preview hashed"
                    .to_owned(),
            });
        }
        if self.run_id != now.run_id {
            return Err(stale("Gate run id", &now.run_id));
        }
        if self.policy_sha256 != now.policy_sha256 {
            return Err(stale("policy fingerprint", &now.policy_sha256));
        }
        if self.acceptances_sha256 != now.acceptances_sha256 {
            return Err(stale("acceptance set", &now.acceptances_sha256));
        }
        Ok(())
    }
}

/// §28's one remediation for everything that is not a file: the preview no longer describes the world.
fn stale(label: &str, now: &str) -> BundleError {
    BundleError::PlanStale {
        detail: format!("the {label} changed after the preview: it is now `{now}`"),
    }
}

/// The leaf of the shipped file whose bytes moved, for an error a person reads. Never its path.
fn changed_leaf(earlier: &[(String, String, u64)], now: &[(String, String, u64)]) -> String {
    earlier
        .iter()
        .zip(now)
        .find(|(was, is)| was != is)
        .map_or_else(
            || "a shipped artifact".to_owned(),
            |(was, _)| sanitize_leaf_name(&was.0),
        )
}

fn observe(request: &BundleRequest<'_>) -> Result<Observation, BundleError> {
    let policy = request.project.policy.clone();
    let target = SnapshotFacts::from_snapshot(request.snapshot);

    // §9's reuse rule: the context is assembled by the same adapter the Gate ran on, with the notes observed
    // by the same call, so a recomputed run id is comparable with a stored one rather than merely similar.
    let notes = policy.require_release_notes.then(|| {
        evidence::observe_release_notes(&request.project.root, &policy.release_notes_path)
    });
    let growth = match request.comparison {
        Some(diff) => {
            if diff.target_snapshot_id != target.snapshot_id {
                return Err(BundleError::Internal {
                    detail: format!(
                        "the comparison names target `{}` while the shipped snapshot is `{}`",
                        diff.target_snapshot_id, target.snapshot_id
                    ),
                });
            }
            evidence::growth_facts(diff)
        }
        None => GateGrowthFacts::without_baseline(),
    };
    let context = evidence::build_context(&evidence::GateRunRequest {
        target: &target,
        growth,
        git: request.git,
        policy: policy.clone(),
        release_notes: notes.clone(),
    });

    let run_id = fingerprint::run_id(&context);
    if let Some(selected) = request.selected_run_id
        && selected != run_id
    {
        return Err(BundleError::GateContextChanged {
            selected: selected.to_owned(),
            recomputed: run_id,
        });
    }
    let evaluation = context.evaluate(&run_id);

    // §10: an acceptance is part of this run's record or it is nothing. The finding has to exist in the
    // recomputed run and has to have been a REVIEW, which is also what keeps an evidence gap unpackageable.
    for acceptance in request.acceptances {
        let finding = evaluation
            .findings
            .iter()
            .find(|candidate| candidate.id == acceptance.finding_id);
        match finding {
            None => {
                return Err(BundleError::Internal {
                    detail: format!(
                        "an acceptance names `{}`, which is not a finding of run `{run_id}`",
                        acceptance.finding_id
                    ),
                });
            }
            Some(found) if found.state != FindingState::Review => {
                return Err(BundleError::Internal {
                    detail: format!(
                        "an acceptance names `{}`, which the run recorded as {}. Only a REVIEW is \
                         acceptable, and an UNKNOWN never becomes one by being signed away",
                        acceptance.finding_id,
                        found.state.as_str()
                    ),
                });
            }
            Some(_) => {}
        }
    }
    let accepted_ids: Vec<String> = request
        .acceptances
        .iter()
        .map(|acceptance| acceptance.finding_id.clone())
        .collect();
    let disposition = evaluation.aggregate_with_acceptances(&accepted_ids);
    // §8 answered before §22: a release that has not earned a bundle is refused on its verdict, so a BLOCK
    // on missing Release Notes reads as the Gate blocking rather than as a file that could not be copied.
    // Core owns the rule; this is the earlier of the two calls to it.
    require_packageable(disposition)?;

    let (version, version_source) = resolve_version(&policy, &context, &evaluation)?;

    // §22 then §23: read and check every source file, then name it safely inside the bundle.
    let shipped = verify_sources(&request.project.root, request.snapshot, &context)?;
    let leaves = bundle_names(&shipped);
    let mut artifacts = shipped
        .iter()
        .zip(&leaves)
        .map(|(row, leaf)| ReleaseArtifact {
            kind: row.kind,
            file_name: leaf.clone(),
            sha256: row.sha256.clone(),
            byte_size: row.byte_size,
        })
        .collect::<Vec<_>>();
    // §52.11: canonical order is a property of the model, and the write order and the manifest both follow
    // it, so pairing a row with a leaf later cannot depend on which directory listing came first.
    artifacts.sort_by(|left, right| {
        ReleaseArtifact::kind_word(left.kind)
            .cmp(ReleaseArtifact::kind_word(right.kind))
            .then_with(|| left.sha256.hex().cmp(right.sha256.hex()))
            .then_with(|| left.byte_size.cmp(&right.byte_size))
            .then_with(|| left.file_name.cmp(&right.file_name))
    });

    // §24: the notes copy is byte-for-byte, identified by the digest the recomputed context already carries.
    let notes_copy = notes.as_ref().map(|fact| match &fact.status {
        GateFileStatus::Present {
            sha256: Some(digest),
        } => {
            let source =
                evidence::join_project_relative(&request.project.root, &policy.release_notes_path);
            std::fs::metadata(&source)
                .map(|metadata| NotesCopy {
                    source,
                    relative: policy.release_notes_path.clone(),
                    sha256: digest.clone(),
                    byte_size: metadata.len(),
                })
                .map_err(|error| BundleError::ReleaseNotesChanged {
                    detail: io_detail(&error),
                })
        }
        GateFileStatus::Present { sha256: None } => Err(BundleError::ReleaseNotesChanged {
            detail:
                "the Gate found the file but read no digest from it, so there is nothing to ship \
                     against"
                    .to_owned(),
        }),
        GateFileStatus::Missing => Err(BundleError::ReleaseNotesChanged {
            detail: format!(
                "`{}` is the configured Release Notes path and nothing is there",
                sanitize_leaf_name(&fact.relative_path)
            ),
        }),
        GateFileStatus::Unreadable { reason } => Err(BundleError::ReleaseNotesChanged {
            detail: format!("`{}`: {reason}", sanitize_leaf_name(&fact.relative_path)),
        }),
    });
    let notes_copy = match notes_copy {
        Some(Ok(copy)) => Some(copy),
        Some(Err(error)) => return Err(error),
        None => None,
    };
    let notes_digest = notes_copy
        .as_ref()
        .map(|copy| {
            Sha256::parse(&copy.sha256).map_err(|_| BundleError::ReleaseNotesChanged {
                detail: "the observed Release Notes digest is not lowercase hex".to_owned(),
            })
        })
        .transpose()?;

    let reviews_document = AcceptedReviewsDto::new(
        &run_id,
        &request
            .acceptances
            .iter()
            .map(|acceptance| AcceptanceDto {
                finding_id: acceptance.finding_id.clone(),
                actor: acceptance.actor.clone(),
                accepted_at: acceptance.accepted_at.clone(),
                reason: acceptance.reason.clone(),
                original_state: ACCEPTANCE_ORIGINAL_STATE,
            })
            .collect::<Vec<_>>(),
        disposition,
    );
    let reviews_json = document_json(&reviews_document);
    let acceptances_sha256 = fingerprint::sha256_hex(reviews_json.as_bytes());

    let model = ReleaseModel {
        snapshot_id: target.snapshot_id.clone(),
        baseline_snapshot_id: request.comparison.map(|diff| diff.base_snapshot_id.clone()),
        gate_run_id: run_id.clone(),
        disposition,
        version,
        version_source,
        acceptances_sha256: Sha256::parse(&acceptances_sha256)
            .expect("a digest of 32 bytes is always 64 lowercase hex"),
        artifacts,
        release_notes: notes_digest.map(|sha256| ReleaseNotesDigest {
            bundle_name: RELEASE_NOTES_NAME.to_owned(),
            sha256,
        }),
        workspace_git: WorkspaceGit {
            head_commit: request.git.facts.head_commit.value().cloned(),
            exact_tag: request.git.facts.exact_tag.value().cloned(),
            dirty: request.git.facts.dirty.value().copied(),
        },
        schema_majors: SchemaMajors::CURRENT,
        fwsight_version: request.fwsight_version.to_owned(),
    }
    .validated()?;
    // §8 is stated once, in Core: `REVIEW` and `BLOCK` both refuse here with `ERR-BUNDLE-6101`.

    // The release id is the digest of the semantic inputs, so it exists before the report prints it and
    // before the manifest names it. Nothing that follows can change an input without changing it.
    let release_id = ReleaseModel::release_id_from(&acceptance_bound_digest(&model));

    let gate_document = GateResultsDto::from_evaluation(
        &evaluation,
        &request.project.policy_sha256,
        request.project.config.schema_version,
    );
    let analysis_document = AnalysisDocumentDto::from_snapshot(request.snapshot, &model.artifacts);
    let comparison_document = request.comparison.map(DiffResultDto::from_diff);

    let mut content = BundleContent::new(
        &model,
        release_id,
        request.project.policy_sha256.clone(),
        &request.project.config.project.name,
        // §27's warnings: the configuration findings the release was prepared under. They name policy keys,
        // never files, so they are the one kind of warning that may cross IPC. What the *build* could not
        // establish travels in `gate-results.json` and `diff.json`, beside the bytes it describes.
        request.project.warnings.clone(),
    );

    // §41's order. Copied files carry the digest of the bytes that were verified; generated documents carry
    // the digest of the bytes composed here and never recomputed again.
    for artifact in &model.artifacts {
        let row = shipped
            .iter()
            .find(|row| row.sha256 == artifact.sha256)
            .expect("the shipped list was built from these rows");
        content.push_copied(
            &format!("{ARTIFACTS_DIR}/{}", artifact.file_name),
            FileRole::ShippedArtifact,
            row.source.clone(),
            artifact.sha256.hex().to_owned(),
            artifact.byte_size,
        );
    }
    content.push_generated(
        ANALYSIS_DOC_NAME,
        FileRole::Analysis,
        document_json(&analysis_document),
    );
    if let Some(diff) = comparison_document.as_ref() {
        content.push_generated(DIFF_DOC_NAME, FileRole::Comparison, document_json(diff));
    }
    content.push_generated(
        GATE_RESULTS_DOC_NAME,
        FileRole::GateResults,
        document_json(&gate_document),
    );
    content.push_generated(
        ACCEPTED_REVIEWS_DOC_NAME,
        FileRole::AcceptedReviews,
        reviews_json,
    );
    if let Some(copy) = &notes_copy {
        content.push_copied(
            RELEASE_NOTES_NAME,
            FileRole::ReleaseNotes,
            copy.source.clone(),
            copy.sha256.clone(),
            copy.byte_size,
        );
    }

    // §7's report is composed from what already exists in the bundle. It prints a digest for every file
    // written before it, and only a name for `SHA256SUMS`, the manifest, and itself.
    let staged = content.index_entries();
    let growth = request.comparison.map(|diff| GrowthRows {
        sections: diff.top_section_growth(REPORT_GROWTH_ROWS),
        symbols: diff.top_symbol_growth(REPORT_GROWTH_ROWS),
    });
    let report = ReleaseBundleReport {
        model: &model,
        release_id: &content.release_id,
        policy_sha256: &content.policy_sha256,
        staged: &staged,
        analysis: &analysis_document,
        compare: comparison_document.as_ref().map(|diff| CompareSummary {
            result: diff,
            top_sections: &growth.as_ref().expect("a comparison carries rows").sections,
            top_symbols: &growth.as_ref().expect("a comparison carries rows").symbols,
        }),
        gate_counts: evaluation.counts,
        gate: &gate_document,
        reviews: &reviews_document,
    };
    content.push_generated(
        REPORT_DOC_NAME,
        FileRole::Report,
        release_render::render_html(&report),
    );

    // Then the two indexes, in that order. After the manifest nothing is regenerated (§41).
    let indexed = content.index_entries();
    let sums = release_render::render_sums(&indexed);
    content.sums_sha256 = fingerprint::sha256_hex(sums.as_bytes());
    content.sums = sums.into_bytes();

    let mut manifest_files = indexed;
    manifest_files.push(ManifestFileDto::new(
        SHA256SUMS_NAME,
        &content.sums_sha256,
        content.sums.len() as u64,
    ));
    let manifest = ReleaseManifestDto::from_parts(
        &model,
        &content.release_id,
        &manifest_files,
        &content.policy_sha256,
    )?;
    content.manifest_json = release_render::render_json(&manifest);
    content.manifest_sha256 = fingerprint::sha256_hex(content.manifest_json.as_bytes());

    let checks = InputChecks {
        run_id,
        policy_sha256: request.project.policy_sha256.clone(),
        acceptances_sha256,
        sources: shipped
            .iter()
            .map(|row| {
                (
                    row.raw_path.clone(),
                    row.sha256.hex().to_owned(),
                    row.byte_size,
                )
            })
            .collect(),
        notes: notes_copy
            .as_ref()
            .map(|copy| (copy.relative.clone(), copy.sha256.clone(), copy.byte_size)),
    };
    Ok(Observation { content, checks })
}

/// §12 in one line: the release id is the digest of the canonical semantic inputs, prefix included.
fn acceptance_bound_digest(model: &ReleaseModel) -> String {
    fingerprint::sha256_hex(model.canonical_release_text().as_bytes())
}

/// The two growth rankings the report prints, taken from Core's selectors.
struct GrowthRows {
    sections: Vec<firmwaresight_core::domain::diff::Contributor>,
    symbols: Vec<firmwaresight_core::domain::diff::Contributor>,
}

/// One verified source row, as §22 requires it to be known before anything is copied.
#[derive(Debug, Clone)]
struct VerifiedRow {
    kind: ArtifactKind,
    sha256: Sha256,
    byte_size: u64,
    /// The path as the snapshot recorded it, for revalidation only.
    raw_path: String,
    source: PathBuf,
}

/// A Release Notes file to copy, as the recomputed context described it (§24).
#[derive(Debug, Clone)]
struct NotesCopy {
    source: PathBuf,
    relative: String,
    sha256: String,
    byte_size: u64,
}

/// Read, hash and check every shipped artifact, in snapshot order (§22, §23).
///
/// The checks run in the prompt's own sequence — stat, regular file, streaming hash, compare hash, compare
/// size — and a failure is a refusal, never an update of the stored digest. The snapshot stays immutable.
fn verify_sources(
    root: &Path,
    snapshot: &BuildSnapshot,
    context: &GateContext,
) -> Result<Vec<VerifiedRow>, BundleError> {
    let mut rows = Vec::new();
    for artifact in snapshot.artifacts() {
        let leaf = sanitize_leaf_name(&artifact.path);
        if !matches!(artifact.kind, ArtifactKind::Elf | ArtifactKind::Map) {
            // §23 ships the ELF and, when supplied, its MAP. A row of another kind is not quietly dropped:
            // a bundle whose manifest omits a file the build recorded is the half-verifiable bundle §44
            // exists to catch.
            return Err(BundleError::Internal {
                detail: format!(
                    "`{leaf}` is a `{}` artifact and this build ships no artifact of that kind",
                    ReleaseArtifact::kind_word(artifact.kind)
                ),
            });
        }
        let path = resolve_source(root, &artifact.path);
        let metadata =
            std::fs::metadata(&path).map_err(|error| BundleError::SourceArtifactChanged {
                name: leaf.clone(),
                detail: if error.kind() == std::io::ErrorKind::NotFound {
                    "the file the build was analyzed from is not there".to_owned()
                } else {
                    io_detail(&error)
                },
            })?;
        if !metadata.is_file() {
            return Err(BundleError::SourceArtifactChanged {
                name: leaf.clone(),
                detail: "the path is not a regular file".to_owned(),
            });
        }
        let digest = fingerprint::file_sha256(&path).map_err(|error| {
            BundleError::SourceArtifactChanged {
                name: leaf.clone(),
                detail: io_detail(&error),
            }
        })?;
        if digest != artifact.sha256.hex() {
            return Err(BundleError::SourceArtifactChanged {
                name: leaf.clone(),
                detail: "its SHA-256 is not the digest the snapshot holds".to_owned(),
            });
        }
        if metadata.len() != artifact.byte_size {
            return Err(BundleError::SourceArtifactChanged {
                name: leaf.clone(),
                detail: format!(
                    "it is {} bytes and the snapshot recorded {}",
                    metadata.len(),
                    artifact.byte_size
                ),
            });
        }
        // The bytes shipped have to be the bytes the Gate judged: a row the assembled context never saw would
        // mean the snapshot and the context came from different builds.
        if !context
            .artifacts
            .iter()
            .any(|fact| fact.kind == artifact.kind && fact.sha256.value() == Some(&digest))
        {
            return Err(BundleError::Internal {
                detail: format!(
                    "`{leaf}` is in the snapshot but not in the Gate context read from it"
                ),
            });
        }
        rows.push(VerifiedRow {
            kind: artifact.kind,
            sha256: artifact.sha256.clone(),
            byte_size: artifact.byte_size,
            raw_path: artifact.path.clone(),
            source: path,
        });
    }
    if rows.is_empty() {
        return Err(BundleError::Release(ReleaseError::NoReleaseArtifacts));
    }
    Ok(rows)
}

/// A snapshot's recorded source path, resolved the one way this module allows: absolute as it was given,
/// relative to the project root. That is the directory the analysis ran from, so a build whose artifact
/// lives elsewhere has to name it absolutely, and anything unresolvable fails closed in
/// [`verify_sources`] rather than shipping a guess.
fn resolve_source(root: &Path, raw: &str) -> PathBuf {
    let path = Path::new(raw);
    if path.is_absolute() {
        return path.to_path_buf();
    }
    evidence::join_project_relative(root, raw)
}

/// The bundle leaves for the verified rows (§23), collision-free even on a case-insensitive filesystem.
///
/// Recognition first — the original leaf, sanitized. Two rows that would land on one name are *both* renamed
/// to Core's content-keyed form, so the pair sorts identically in every bundle and neither file wins by
/// whichever directory entry arrived first.
fn bundle_names(rows: &[VerifiedRow]) -> Vec<String> {
    let base: Vec<String> = rows
        .iter()
        .map(|row| sanitize_leaf_name(&row.raw_path))
        .collect();
    let mut counted: std::collections::BTreeMap<String, usize> = std::collections::BTreeMap::new();
    for name in &base {
        *counted.entry(name.to_lowercase()).or_insert(0) += 1;
    }
    base.iter()
        .zip(rows)
        .map(|(name, row)| {
            if counted[&name.to_lowercase()] > 1 {
                disambiguated_name(row.kind, &row.sha256, name)
            } else {
                name.clone()
            }
        })
        .collect()
}

/// §11's precedence, read off the context the Gate judged rather than from a dialog.
///
/// `release.expected_version` first, but only when the version rule passed — a version the Gate never
/// endorsed is not a release version. Otherwise the `version` capture the exact tag yielded under
/// `[version] pattern`. Never the app version, a file name, or an import timestamp.
fn resolve_version(
    policy: &GatePolicy,
    context: &GateContext,
    evaluation: &GateEvaluation,
) -> Result<(ReleaseVersion, ReleaseVersionSource), BundleError> {
    let endorsed = evaluation
        .finding(GateRuleId::VersionMatchesPolicy)
        .is_some_and(|finding| finding.state == FindingState::Pass);
    let expected = policy
        .version
        .as_ref()
        .and_then(|declared| declared.expected_version.clone());
    let captured = context
        .version
        .as_ref()
        .and_then(|facts| facts.captured_version.value().cloned());
    let resolved = expected
        .filter(|_| endorsed)
        .map(|value| (value, ReleaseVersionSource::ExpectedVersion))
        .or_else(|| captured.map(|value| (value, ReleaseVersionSource::GitTagCapture)));
    let (text, source) = resolved.ok_or_else(|| {
        let reason = match (endorsed, policy.version.is_some()) {
            (false, true) => "`release.expected_version` is configured but the Gate's version rule did not \
                 pass, and no exact tag yielded a `version` capture"
                .to_owned(),
            (true, true) | (false, false) => {
                "the `[version]` policy's pattern matched no tag carrying a `version` capture, and no \
                 `release.expected_version` resolved"
                    .to_owned()
            }
            (true, false) => "no `[version]` policy is configured, so there is no tag pattern a release \
                 version could be read from"
                .to_owned(),
        };
        BundleError::Release(ReleaseError::VersionUnavailable { reason })
    })?;
    Ok((
        ReleaseVersion::parse(&text).map_err(BundleError::Release)?,
        source,
    ))
}

// --------------------------------------------------------------------------- content

/// One file the plan will write.
#[derive(Debug, Clone)]
struct StagedFile {
    /// Bundle-relative and `/`-separated.
    path: String,
    role: FileRole,
    body: Body,
    sha256: String,
    byte_size: u64,
}

/// Either bytes this module composed, or a verified source file copied without being opened again in a way
/// that could change them. §24's notes copy and §22's artifacts are byte-for-byte by definition.
#[derive(Debug, Clone)]
enum Body {
    Composed(Vec<u8>),
    Copied(PathBuf),
}

/// Every byte of the bundle, in §41's order, plus the two indexes appended after the payload.
#[derive(Debug, Clone)]
struct BundleContent {
    model: ReleaseModel,
    release_id: String,
    policy_sha256: String,
    directory_name: String,
    files: Vec<StagedFile>,
    /// The configuration findings the release was prepared under, carried into the preview (§27). They name
    /// policy keys rather than files, so none of them can be a host path.
    warnings: Vec<String>,
    sums: Vec<u8>,
    sums_sha256: String,
    manifest_json: String,
    manifest_sha256: String,
}

impl BundleContent {
    fn new(
        model: &ReleaseModel,
        release_id: String,
        policy_sha256: String,
        project_name: &str,
        warnings: Vec<String>,
    ) -> Self {
        // §29's proposed name, built from facts rather than from a folder the caller chose.
        let directory_name = format!(
            "{}-{}-{}",
            sanitize_leaf_name(project_name),
            model.version.as_str(),
            ReleaseId::parse(&release_id)
                .expect("the release id was assembled by this module")
                .short_hex()
        );
        Self {
            model: model.clone(),
            release_id,
            policy_sha256,
            directory_name,
            warnings,
            files: Vec::new(),
            sums: Vec::new(),
            sums_sha256: String::new(),
            manifest_json: String::new(),
            manifest_sha256: String::new(),
        }
    }

    fn push_generated(&mut self, path: &str, role: FileRole, text: String) {
        let byte_size = text.len() as u64;
        let sha256 = fingerprint::sha256_hex(text.as_bytes());
        self.files.push(StagedFile {
            path: path.to_owned(),
            role,
            body: Body::Composed(text.into_bytes()),
            sha256,
            byte_size,
        });
    }

    fn push_copied(
        &mut self,
        path: &str,
        role: FileRole,
        source: PathBuf,
        sha256: String,
        byte_size: u64,
    ) {
        self.files.push(StagedFile {
            path: path.to_owned(),
            role,
            body: Body::Copied(source),
            sha256,
            byte_size,
        });
    }

    /// The `files[]` shape the manifest and `SHA256SUMS` are both built from, in Core's single ordering.
    fn index_entries(&self) -> Vec<ManifestFileDto> {
        let mut entries: Vec<ManifestFileDto> = self
            .files
            .iter()
            .map(|file| ManifestFileDto::new(&file.path, &file.sha256, file.byte_size))
            .collect();
        entries.sort_by(|left, right| bundle_path_order(&left.path, &right.path));
        entries
    }

    fn preview(&self, plan_id: String) -> BundlePreview {
        let mut files: Vec<PlannedFile> = self
            .files
            .iter()
            .map(|file| PlannedFile {
                path: file.path.clone(),
                role: file.role,
                byte_size: file.byte_size,
                sha256: file.sha256.clone(),
            })
            .collect();
        files.push(PlannedFile {
            path: SHA256SUMS_NAME.to_owned(),
            role: FileRole::ChecksumIndex,
            byte_size: self.sums.len() as u64,
            sha256: self.sums_sha256.clone(),
        });
        files.push(PlannedFile {
            path: MANIFEST_DOC_NAME.to_owned(),
            role: FileRole::Manifest,
            byte_size: self.manifest_json.len() as u64,
            sha256: self.manifest_sha256.clone(),
        });
        files.sort_by(|left, right| bundle_path_order(&left.path, &right.path));
        BundlePreview {
            plan_id,
            release_id: self.release_id.clone(),
            release_version: self.model.version.as_str().to_owned(),
            snapshot_id: self.model.snapshot_id.clone(),
            baseline_snapshot_id: self.model.baseline_snapshot_id.clone(),
            gate_run_id: self.model.gate_run_id.clone(),
            disposition: self.model.disposition.as_str(),
            files,
            warnings: self.warnings.clone(),
        }
    }
}

// --------------------------------------------------------------------------- writing

/// A process-local counter, so no two plans or staging directories in one session share a name. §26 asks for
/// `bundle-<pid>-<counter>` and forbids a random dependency; an atomic counter is the whole of it.
static SEQUENCE: AtomicUsize = AtomicUsize::new(0);

fn next_plan_id() -> String {
    format!(
        "bundle-{}-{}",
        std::process::id(),
        SEQUENCE.fetch_add(1, Ordering::Relaxed) + 1
    )
}

/// The display half of an I/O failure: its kind, never the path it tried. `std::io::Error`'s `Display`
/// quotes the path, and a path has no business in a preview, a release record or a UI error card.
fn io_detail(error: &std::io::Error) -> String {
    format!("a filesystem operation failed ({:?})", error.kind())
}

/// A sibling directory of `parent` that cannot collide with a bundle or with another session's work.
fn sibling(parent: &Path, purpose: &str) -> PathBuf {
    parent.join(format!(
        ".firmwaresight-{purpose}-{}-{}",
        std::process::id(),
        SEQUENCE.fetch_add(1, Ordering::Relaxed)
    ))
}

/// Write the staged tree: the payload in §41's order, then `SHA256SUMS`, then the manifest.
fn write_tree(content: &BundleContent, staging: &Path) -> Result<(), BundleError> {
    std::fs::create_dir_all(staging.join(ARTIFACTS_DIR)).map_err(|error| {
        BundleError::WriteFailed {
            name: ARTIFACTS_DIR.to_owned(),
            detail: io_detail(&error),
        }
    })?;
    for file in &content.files {
        match &file.body {
            Body::Composed(bytes) => write_bytes(staging, &file.path, bytes)?,
            Body::Copied(source) => copy_file(source, staging, &file.path)?,
        }
    }
    write_bytes(staging, SHA256SUMS_NAME, &content.sums)?;
    write_bytes(staging, MANIFEST_DOC_NAME, content.manifest_json.as_bytes())
}

fn bundle_target(staging: &Path, relative: &str) -> PathBuf {
    staging.join(relative.replace('/', std::path::MAIN_SEPARATOR_STR))
}

fn write_bytes(staging: &Path, relative: &str, bytes: &[u8]) -> Result<(), BundleError> {
    let mut file = create_file(staging, relative)?;
    file.write_all(bytes)
        .map_err(|error| BundleError::WriteFailed {
            name: relative.to_owned(),
            detail: io_detail(&error),
        })?;
    sync(file, relative)
}

/// Copy a verified source file into the bundle without rewriting it (§7, §24).
fn copy_file(source: &Path, staging: &Path, relative: &str) -> Result<(), BundleError> {
    let mut reader = std::fs::File::open(source).map_err(|error| BundleError::WriteFailed {
        name: relative.to_owned(),
        detail: io_detail(&error),
    })?;
    let mut file = create_file(staging, relative)?;
    std::io::copy(&mut reader, &mut file).map_err(|error| BundleError::WriteFailed {
        name: relative.to_owned(),
        detail: io_detail(&error),
    })?;
    sync(file, relative)
}

fn create_file(staging: &Path, relative: &str) -> Result<std::fs::File, BundleError> {
    let target = bundle_target(staging, relative);
    if let Some(parent) = target.parent() {
        std::fs::create_dir_all(parent).map_err(|error| BundleError::WriteFailed {
            name: relative.to_owned(),
            detail: io_detail(&error),
        })?;
    }
    std::fs::File::create(&target).map_err(|error| BundleError::WriteFailed {
        name: relative.to_owned(),
        detail: io_detail(&error),
    })
}

/// §31 step 3, "where appropriate or practical": a bundle a stranger verifies on another machine has to be
/// on the disk, not in a process buffer, before its directory is renamed into place. The flush runs on the
/// write handle, because a read-only handle cannot flush a file on Windows.
fn sync(file: std::fs::File, relative: &str) -> Result<(), BundleError> {
    file.sync_all().map_err(|error| BundleError::WriteFailed {
        name: relative.to_owned(),
        detail: io_detail(&error),
    })
}

/// Discard a staging tree this module wrote. Never called on a destination, and never on a directory that
/// was not created here.
fn discard(staging: &Path) {
    let _ = std::fs::remove_dir_all(staging);
}

/// Publish the staged tree, returning the backup directory when an existing bundle was moved aside.
///
/// An absent destination is one rename. An occupied one is reached only with explicit authorization and only
/// after §32's recognition test, and the predecessor is renamed aside rather than deleted, so a failed swap
/// leaves the release owner with exactly the bundle they had.
fn replace_directory(
    staging: &Path,
    destination: &Path,
    overwrite: bool,
    display: &str,
) -> Result<Option<PathBuf>, BundleError> {
    if !destination.exists() {
        rename(staging, destination, display)?;
        return Ok(None);
    }
    if !overwrite {
        // Unreachable through this module's own API — `publish` refuses first. Stated as a refusal rather
        // than a panic, because this is the last function standing between a rename and a person's folder.
        return Err(BundleError::DestinationExists {
            display: display.to_owned(),
        });
    }
    let parent = destination
        .parent()
        .map_or_else(|| PathBuf::from("."), Path::to_path_buf);
    let backup = sibling(&parent, "replaced");
    rename(destination, &backup, display)?;
    if let Err(error) = rename(staging, destination, display) {
        // Roll the predecessor back before anything is reported.
        let restored = rename(&backup, destination, display);
        return Err(match restored {
            Ok(()) => error,
            Err(rollback) => BundleError::WriteFailed {
                name: display.to_owned(),
                detail: format!(
                    "{} The bundle that was moved aside is still in the folder under the name `{}`.",
                    rollback,
                    backup.file_name().map_or_else(
                        || "a sibling name".to_owned(),
                        |name| name.to_string_lossy().to_string()
                    )
                ),
            },
        });
    }
    Ok(Some(backup))
}

fn rename(from: &Path, to: &Path, display: &str) -> Result<(), BundleError> {
    std::fs::rename(from, to).map_err(|error| BundleError::WriteFailed {
        name: display.to_owned(),
        detail: io_detail(&error),
    })
}

// --------------------------------------------------------------------------- recognition (§32)

/// Whether one directory is a bundle a previous FirmwareSight wrote.
///
/// The test is the smallest thing that can be trusted about a directory: a manifest that parses, says
/// version 1, names FirmwareSight as its producer, and carries a release id shaped like one. Anything else is
/// somebody else's folder, and §31 forbids replacing it because a flag was passed.
///
/// # Errors
///
/// [`BundleError::WriteFailed`] when a manifest is present but cannot be read at all, which is a filesystem
/// problem rather than the "not a bundle" answer `false` means.
pub fn is_recognizable_bundle(root: &Path) -> Result<bool, BundleError> {
    let manifest = root.join(MANIFEST_DOC_NAME);
    if !manifest.is_file() {
        return Ok(false);
    }
    let text = std::fs::read_to_string(&manifest).map_err(|error| BundleError::WriteFailed {
        name: MANIFEST_DOC_NAME.to_owned(),
        detail: io_detail(&error),
    })?;
    let Ok(value) = serde_json::from_str::<serde_json::Value>(&text) else {
        return Ok(false);
    };
    let version = value
        .get("schema_version")
        .and_then(serde_json::Value::as_i64)
        .unwrap_or_default();
    let product = value
        .pointer("/generated_by/product")
        .and_then(serde_json::Value::as_str)
        .unwrap_or_default();
    let id = value
        .pointer("/release/id")
        .and_then(serde_json::Value::as_str)
        .unwrap_or_default();
    Ok(version == 1 && product == "FirmwareSight" && ReleaseId::parse(id).is_ok())
}

// --------------------------------------------------------------------------- verification (§44)

/// Verify a bundle from its own bytes, with no project, no database and no FirmwareSight state (§45).
///
/// This is the engine §44 asks for, used three times: on the staged tree before publication, on the published
/// directory after it, and on a bundle that has been copied somewhere else entirely. It proves the bytes match
/// the two lists and that the lists describe the release they name — an integrity and consistency statement
/// about the bundle as written, and nothing about who wrote it (§62).
///
/// # Errors
///
/// [`BundleError::VerificationFailed`] for anything that makes the bundle not what this build writes, and
/// [`BundleError::WriteFailed`] for a file the bundle should hold and the filesystem will not hand over.
pub fn verify_bundle(root: &Path) -> Result<BundleVerification, BundleError> {
    let files = listed_files(root)?;
    let names: Vec<&str> = files.iter().map(|(name, _)| name.as_str()).collect();

    for required in REQUIRED_BUNDLE_FILES {
        if !names.contains(&required) {
            return Err(fail(format!("`{required}` is not in the bundle")));
        }
    }
    if !names
        .iter()
        .any(|name| name.starts_with(&format!("{ARTIFACTS_DIR}/")))
    {
        return Err(fail(
            "the bundle ships no file under `artifacts/`".to_owned(),
        ));
    }
    for name in &names {
        if !is_safe_bundle_relative_path(name) {
            return Err(fail(format!("`{name}` is not a safe bundle-relative path")));
        }
        let allowed = REQUIRED_BUNDLE_FILES
            .iter()
            .chain(OPTIONAL_BUNDLE_FILES.iter())
            .any(|known| known == name)
            || name.starts_with(&format!("{ARTIFACTS_DIR}/"));
        if !allowed {
            return Err(fail(format!(
                "`{name}` is not a file this bundle layout writes"
            )));
        }
    }
    // Two names that differ only in case are one file to a Windows reader, and a bundle read on whichever
    // host did not write it is half a bundle.
    let mut folded: Vec<String> = names.iter().map(|name| name.to_lowercase()).collect();
    let counted = folded.len();
    folded.sort();
    folded.dedup();
    if folded.len() != counted {
        return Err(fail(
            "two bundle paths name the same file on a case-insensitive filesystem".to_owned(),
        ));
    }

    let manifest = read_json(root, MANIFEST_DOC_NAME)?;
    check_document_contract(MANIFEST_DOC_NAME, &manifest)?;
    let sums = read_text(root, SHA256SUMS_NAME)?;
    let indexed = manifest_file_list(&manifest)?;

    // §21's format, then §44's byte check: every listed digest is the digest of the bytes that are there.
    let mut listed: Vec<(String, String)> = Vec::new();
    for line in sums.split('\n').filter(|line| !line.is_empty()) {
        let Some((digest, path)) = line.split_once("  ") else {
            return Err(fail(format!(
                "`SHA256SUMS` carries a line that is not `<digest>  <path>`: {line}"
            )));
        };
        Sha256::parse(digest).map_err(|_| {
            fail(format!(
                "`SHA256SUMS` carries a digest that is not 64 lowercase hex: {digest}"
            ))
        })?;
        if path.is_empty() || !is_safe_bundle_relative_path(path) {
            return Err(fail(format!("`SHA256SUMS` names `{path}`")));
        }
        listed.push((path.to_owned(), digest.to_owned()));
    }
    for excluded in SUMS_EXCLUDED_NAMES {
        if listed.iter().any(|(path, _)| path == excluded) {
            return Err(fail(format!(
                "`SHA256SUMS` lists `{excluded}`, which it cannot hash without a fixed point"
            )));
        }
    }
    for (path, digest) in &listed {
        let actual = digest_of(&read_bytes(root, path)?);
        if &actual != digest {
            return Err(fail(format!(
                "`{path}` hashes to {actual}, not the {digest} `SHA256SUMS` records"
            )));
        }
    }
    let listed_paths: Vec<String> = listed.iter().map(|(path, _)| path.clone()).collect();
    if !ordered_by_bundle_path(&listed_paths) {
        return Err(fail(
            "`SHA256SUMS` is not in the order this build sorts it into".to_owned(),
        ));
    }

    // The manifest's own list, checked the same way, covering everything the bundle holds — `SHA256SUMS`
    // included, itself excluded (§20).
    let mut manifest_paths: Vec<String> = Vec::new();
    for (path, digest, size) in &indexed {
        if path == MANIFEST_DOC_NAME {
            return Err(fail(
                "`release-manifest.json` indexes itself, which is the faked self-hash §20 refuses"
                    .to_owned(),
            ));
        }
        let bytes = read_bytes(root, path).map_err(|_| {
            fail(format!(
                "the manifest indexes `{path}`, which is not in the bundle"
            ))
        })?;
        if bytes.len() as u64 != *size {
            return Err(fail(format!(
                "`{path}` is {} bytes and the manifest says {size}",
                bytes.len()
            )));
        }
        let actual = digest_of(&bytes);
        if &actual != digest {
            return Err(fail(format!(
                "`{path}` hashes to {actual}, not the {digest} the manifest records"
            )));
        }
        manifest_paths.push(path.clone());
    }
    for required in REQUIRED_BUNDLE_FILES
        .iter()
        .filter(|name| **name != MANIFEST_DOC_NAME)
    {
        if !manifest_paths.iter().any(|path| path == required) {
            return Err(fail(format!("the manifest does not index `{required}`")));
        }
    }
    for name in &names {
        if *name != MANIFEST_DOC_NAME && !manifest_paths.iter().any(|path| path == name) {
            return Err(fail(format!(
                "`{name}` is in the bundle but not indexed by the manifest"
            )));
        }
    }
    if !ordered_by_bundle_path(&manifest_paths) {
        return Err(fail(
            "`release-manifest.json` files[] is not in the order this build sorts it into"
                .to_owned(),
        ));
    }

    // §44's five "schema valid" bullets, checked against the contracts compiled into this binary rather
    // than against a `schemas/` directory the reader may not have. The report reaches nothing outside the
    // bundle, and no generated document carries a host path. The copied Release Notes are exempt from the
    // last two checks: they are the release owner's bytes, byte-for-byte (§24), and a URL or a path inside
    // a sentence about the release is their business, not a leak from this engine.
    let analysis = read_json(root, ANALYSIS_DOC_NAME)?;
    let gate = read_json(root, GATE_RESULTS_DOC_NAME)?;
    let reviews = read_json(root, ACCEPTED_REVIEWS_DOC_NAME)?;
    check_document_contract(ANALYSIS_DOC_NAME, &analysis)?;
    check_document_contract(GATE_RESULTS_DOC_NAME, &gate)?;
    check_document_contract(ACCEPTED_REVIEWS_DOC_NAME, &reviews)?;
    if names.contains(&DIFF_DOC_NAME) {
        let diff = read_json(root, DIFF_DOC_NAME)?;
        check_document_contract(DIFF_DOC_NAME, &diff)?;
    }
    let report_html = read_text(root, REPORT_DOC_NAME)?;
    if report_html.contains("<script")
        || report_html.contains("http://")
        || report_html.contains("https://")
        || report_html.contains("@import")
        || report_html.contains("<link")
    {
        return Err(fail(
            "`release-report.html` reaches outside the bundle it sits in".to_owned(),
        ));
    }
    for name in GENERATED_TEXT_DOCUMENTS {
        // `diff.json` and the rest are conditional on the release, so the bundle is asked whether it carries
        // one rather than reading a file that a release with no baseline never wrote.
        if !names.contains(&name) {
            continue;
        }
        if let Some(found) = host_path_in(&read_text(root, name)?) {
            return Err(fail(format!("`{name}` carries a host path: {found}")));
        }
    }
    if host_path_in(&sums).is_some() {
        return Err(fail(
            "`SHA256SUMS` names something that is not a bundle-relative path".to_owned(),
        ));
    }

    // The strongest check the bytes allow: re-derive what the release id is the digest of from the bundle
    // alone, and require it to equal the id the bundle claims (§44).
    let claimed = manifest
        .pointer("/release/id")
        .and_then(serde_json::Value::as_str)
        .ok_or_else(|| fail("`release-manifest.json` carries no release id".to_owned()))?;
    let reviews_bytes = read_bytes(root, ACCEPTED_REVIEWS_DOC_NAME)?;
    let rebuilt = model_from_documents(&manifest, &analysis, &reviews, &indexed, &reviews_bytes)?;
    let recomputed = ReleaseModel::release_id_from(&acceptance_bound_digest(&rebuilt));
    if recomputed != claimed {
        return Err(fail(format!(
            "the bundle's documents describe release `{recomputed}`, but it claims `{claimed}`"
        )));
    }

    Ok(BundleVerification {
        release_id: claimed.to_owned(),
        file_count: files.len(),
        total_bytes: files.iter().map(|(_, size)| *size).sum(),
        artifact_count: manifest_paths
            .iter()
            .filter(|path| path.starts_with(&format!("{ARTIFACTS_DIR}/")))
            .count(),
        carries_comparison: names.contains(&DIFF_DOC_NAME),
        carries_release_notes: names.contains(&RELEASE_NOTES_NAME),
    })
}

fn fail(detail: String) -> BundleError {
    BundleError::VerificationFailed { detail }
}

/// The two shapes a host path takes in text this engine wrote: a drive prefix (`C:/`, `d:\`) and a
/// POSIX-absolute home, mount or temporary directory. `urn:firmwaresight:…` and `sha256:…` are not drive
/// prefixes, because the character before the colon is not a lone letter.
fn host_path_in(text: &str) -> Option<&'static str> {
    let bytes = text.as_bytes();
    for index in 0..bytes.len().saturating_sub(2) {
        let (first, middle, last) = (bytes[index], bytes[index + 1], bytes[index + 2]);
        if middle != b':' || !matches!(last, b'/' | b'\\') || !first.is_ascii_alphabetic() {
            continue;
        }
        let standalone = index == 0 || !bytes[index - 1].is_ascii_alphanumeric();
        if standalone {
            return Some("a Windows drive path");
        }
    }
    for marker in [
        "/home/",
        "/Users/",
        "/mnt/",
        "/private/var/",
        "/tmp/",
        "/var/folders/",
    ] {
        if text.contains(marker) {
            return Some("an absolute POSIX path");
        }
    }
    None
}

/// Every file in the tree, bundle-relative and with its size, in Core's single ordering.
fn listed_files(root: &Path) -> Result<Vec<(String, u64)>, BundleError> {
    let mut out = Vec::new();
    let mut stack = vec![(root.to_path_buf(), String::new())];
    while let Some((directory, prefix)) = stack.pop() {
        let entries = std::fs::read_dir(&directory).map_err(|error| BundleError::WriteFailed {
            name: if prefix.is_empty() {
                ".".to_owned()
            } else {
                prefix.clone()
            },
            detail: io_detail(&error),
        })?;
        for entry in entries {
            let entry = entry.map_err(|error| BundleError::WriteFailed {
                name: prefix.clone(),
                detail: io_detail(&error),
            })?;
            let name = entry.file_name().to_string_lossy().to_string();
            let relative = if prefix.is_empty() {
                name.clone()
            } else {
                format!("{prefix}/{name}")
            };
            // `symlink_metadata`, not `DirEntry::file_type`: the last one follows the link, so a symlink to
            // a directory outside the bundle would be walked instead of refused.
            let metadata = std::fs::symlink_metadata(entry.path()).map_err(|error| {
                BundleError::WriteFailed {
                    name: relative.clone(),
                    detail: io_detail(&error),
                }
            })?;
            if metadata.file_type().is_symlink() {
                return Err(fail(format!(
                    "`{relative}` is a symlink, which no bundle writes"
                )));
            }
            if metadata.is_dir() {
                stack.push((entry.path(), relative));
                continue;
            }
            if !metadata.is_file() {
                return Err(fail(format!(
                    "`{relative}` is neither a file nor a directory"
                )));
            }
            out.push((relative, metadata.len()));
        }
    }
    out.sort_by(|left, right| bundle_path_order(&left.0, &right.0));
    Ok(out)
}

fn read_bytes(root: &Path, relative: &str) -> Result<Vec<u8>, BundleError> {
    std::fs::read(bundle_target(root, relative)).map_err(|error| BundleError::WriteFailed {
        name: relative.to_owned(),
        detail: io_detail(&error),
    })
}

fn read_text(root: &Path, relative: &str) -> Result<String, BundleError> {
    let bytes = read_bytes(root, relative)?;
    String::from_utf8(bytes).map_err(|_| {
        fail(format!(
            "`{relative}` is not UTF-8, so no reader can open it as text"
        ))
    })
}

fn read_json(root: &Path, relative: &str) -> Result<serde_json::Value, BundleError> {
    let text = read_text(root, relative)?;
    serde_json::from_str(&text).map_err(|error| {
        fail(format!(
            "`{relative}` does not parse as one JSON document: {error}"
        ))
    })
}

fn digest_of(bytes: &[u8]) -> String {
    fingerprint::sha256_hex(bytes)
}

/// One `files[]` entry of the manifest, as the verifier needs it.
type ManifestEntry = (String, String, u64);

fn manifest_file_list(value: &serde_json::Value) -> Result<Vec<ManifestEntry>, BundleError> {
    let entries = value
        .get("files")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| fail("`release-manifest.json` carries no `files` array".to_owned()))?;
    let mut out = Vec::with_capacity(entries.len());
    for entry in entries {
        let path = entry
            .get("path")
            .and_then(serde_json::Value::as_str)
            .ok_or_else(|| fail("a manifest `files` entry names no path".to_owned()))?;
        let digest = entry
            .get("sha256")
            .and_then(serde_json::Value::as_str)
            .ok_or_else(|| fail(format!("`{path}` is indexed with no digest")))?;
        let size = entry
            .get("size")
            .and_then(serde_json::Value::as_u64)
            .ok_or_else(|| fail(format!("`{path}` is indexed with no size")))?;
        Sha256::parse(digest).map_err(|_| {
            fail(format!(
                "`{path}` is indexed with a digest that is not lowercase hex"
            ))
        })?;
        out.push((path.to_owned(), digest.to_owned(), size));
    }
    Ok(out)
}

fn ordered_by_bundle_path(paths: &[String]) -> bool {
    paths
        .windows(2)
        .all(|pair| bundle_path_order(&pair[0], &pair[1]) != std::cmp::Ordering::Greater)
}

/// The key one document spells its contract major under.
///
/// `analysis:1` (§14) and `diff:1` (§16) are camelCase; `gate-results:1`, `accepted-reviews:1` and
/// `release-manifest:1` are snake_case, and each keeps whichever spelling it was published with, because
/// re-spelling a frozen key is a semantics change that needs a major version (`04_TECH/26`). The table is
/// here rather than in a schema file because §45 makes a relocated bundle verifiable from its own bytes, and
/// a shipped binary has no `schemas/` directory to read. A verifier that assumed one spelling would refuse
/// every analysis document this build itself writes.
fn schema_version_key(document: &str) -> &'static str {
    if document == ANALYSIS_DOC_NAME || document == DIFF_DOC_NAME {
        "schemaVersion"
    } else {
        "schema_version"
    }
}

fn check_schema_identity(value: &serde_json::Value, name: &str) -> Result<(), BundleError> {
    let key = schema_version_key(name);
    let version = value
        .get(key)
        .and_then(serde_json::Value::as_u64)
        .ok_or_else(|| fail(format!("`{name}` carries no `{key}`")))?;
    if version != 1 {
        return Err(fail(format!(
            "`{name}` is major {version}, and this build reads major 1"
        )));
    }
    Ok(())
}

/// How many contract violations one refusal quotes.
///
/// A tampered `symbols` array can fail the same subschema on every row, and a message that recites all of
/// them buries the point. The count is always stated, so a reader knows whether they are looking at the
/// whole of the damage or the first eight of it.
const QUOTED_FAILURES: usize = 8;

/// Check one bundle document against the portable contract its name selects (§44).
///
/// The identity check runs first on purpose. A bundle written under a different major is one clear refusal
/// — "this build reads major 1" — while validating it against the contract this build carries would produce a
/// page of keyword failures for keys that document was never written under, and a page of noise reads like
/// corruption when the real answer is a version mismatch.
///
/// A document that carries major 1 and still fails is what §44 calls a bundle that is not valid: something in
/// it is not the shape this build composes, and every failure is reported with the JSON pointer it was found
/// at so the reader can locate it without reopening the project.
fn check_document_contract(name: &str, value: &serde_json::Value) -> Result<(), BundleError> {
    check_schema_identity(value, name)?;
    let failures =
        schemas::validate(name, value).map_err(|reason| fail(format!("`{name}`: {reason}")))?;
    if failures.is_empty() {
        return Ok(());
    }
    let quoted = failures
        .iter()
        .take(QUOTED_FAILURES)
        .map(ToString::to_string)
        .collect::<Vec<_>>()
        .join("; ");
    let remainder = if failures.len() > QUOTED_FAILURES {
        format!(", and {} more", failures.len() - QUOTED_FAILURES)
    } else {
        String::new()
    };
    Err(fail(format!(
        "`{name}` does not satisfy the contract it declares: {quoted}{remainder}"
    )))
}

/// Rebuild the semantic inputs from the bundle's own documents, so a release id is checked against the bytes
/// rather than against the plan that produced them.
///
/// Every field comes out of a file: the manifest for the identity, version source and workspace facts, the
/// analysis document for which kind of artifact each shipped leaf is, the file list for the digests, and the
/// acceptance document's own bytes for the digest that binds them.
fn model_from_documents(
    manifest: &serde_json::Value,
    analysis: &serde_json::Value,
    reviews: &serde_json::Value,
    indexed: &[ManifestEntry],
    reviews_bytes: &[u8],
) -> Result<ReleaseModel, BundleError> {
    let field = |pointer: &str| {
        manifest
            .pointer(pointer)
            .and_then(serde_json::Value::as_str)
            .map(str::to_owned)
    };
    let required = |pointer: &str| {
        field(pointer).ok_or_else(|| {
            fail(format!(
                "`release-manifest.json` carries no value at `{pointer}`"
            ))
        })
    };
    let version_source = match field("/extensions/release_version_source").as_deref() {
        Some("release.expected_version") => ReleaseVersionSource::ExpectedVersion,
        Some("git_tag.capture") => ReleaseVersionSource::GitTagCapture,
        other => {
            return Err(fail(format!(
                "`release_version_source` is {other:?}, and a release version comes from one of exactly \
                 two places"
            )));
        }
    };
    // §8 again, this time from the reader's side: a bundle that aggregates to anything but PASS is not a
    // release, whatever its manifest claims.
    let disposition = reviews
        .pointer("/extensions/overall_effective_severity")
        .and_then(serde_json::Value::as_str)
        .unwrap_or_default();
    if disposition != EffectiveSeverity::Pass.as_str() {
        return Err(fail(format!(
            "`accepted-reviews.json` aggregates to {disposition}, and only a PASS disposition is a release"
        )));
    }

    // The kind words live in `analysis.json`, keyed by the leaf each shipped file carries in this bundle.
    let mut kinds: Vec<(String, ArtifactKind)> = Vec::new();
    if let Some(rows) = analysis
        .get("artifacts")
        .and_then(serde_json::Value::as_array)
    {
        for row in rows {
            let name = row.get("fileName").and_then(serde_json::Value::as_str);
            let kind = row.get("kind").and_then(serde_json::Value::as_str);
            if let (Some(name), Some(word)) = (name, kind)
                && let Some(parsed) = ArtifactKind::from_word(word)
            {
                kinds.push((name.to_owned(), parsed));
            }
        }
    }
    let artifacts = indexed
        .iter()
        .filter_map(|(path, digest, size)| {
            path.strip_prefix(&format!("{ARTIFACTS_DIR}/"))
                .map(|leaf| (leaf, digest, size))
        })
        .map(|(leaf, digest, size)| {
            let kind = kinds
                .iter()
                .find(|(name, _)| name == leaf)
                .map(|(_, kind)| *kind)
                .ok_or_else(|| {
                    fail(format!(
                        "`{ARTIFACTS_DIR}/{leaf}` ships, and no document says what kind of artifact it is"
                    ))
                })?;
            Ok(ReleaseArtifact {
                kind,
                file_name: leaf.to_owned(),
                sha256: Sha256::parse(digest).expect("the manifest list was parsed above"),
                byte_size: *size,
            })
        })
        .collect::<Result<Vec<_>, BundleError>>()?;

    let notes = indexed
        .iter()
        .find(|(path, _, _)| path == RELEASE_NOTES_NAME)
        .map(|(_, digest, _)| digest.clone());
    let declared = field("/release/notes");
    let release_notes = match (declared, notes) {
        (Some(_), None) | (None, Some(_)) => {
            return Err(fail(
                "`release.notes` and the bundle's `release-notes.md` disagree about whether the release \
                 has notes"
                    .to_owned(),
            ));
        }
        (Some(name), Some(digest)) => Some(ReleaseNotesDigest {
            bundle_name: name,
            sha256: Sha256::parse(&digest).expect("the manifest list was parsed above"),
        }),
        (None, None) => None,
    };

    let model = ReleaseModel {
        snapshot_id: required("/build/snapshot_id")?,
        baseline_snapshot_id: field("/extensions/baseline_snapshot_id"),
        gate_run_id: required("/extensions/gate_run_id")?,
        disposition: EffectiveSeverity::Pass,
        version: ReleaseVersion::parse(&required("/release/version")?)
            .map_err(BundleError::Release)?,
        version_source,
        acceptances_sha256: Sha256::parse(&digest_of(reviews_bytes))
            .expect("a digest this module computed parses"),
        artifacts,
        release_notes,
        workspace_git: WorkspaceGit {
            head_commit: field("/build/git_commit"),
            exact_tag: field("/build/git_tag"),
            dirty: manifest
                .pointer("/build/git_dirty")
                .and_then(serde_json::Value::as_bool),
        },
        schema_majors: SchemaMajors::CURRENT,
        fwsight_version: required("/generated_by/version")?,
    };
    model.validated().map_err(BundleError::Release)
}

#[cfg(test)]
mod tests;
